"""baseline：16 张表（等价于此前 create_all）

存量库（alembic 引入前由 create_all 直建）不重放本迁移——run_migrations
检测到 meta 表已存在且无 alembic_version 时自动 stamp head。

Revision ID: 0001_baseline
Revises:
Create Date: 2026-09-26 13:09:59.290970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0001_baseline'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auditlog',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('target', sa.String(), nullable=False),
    sa.Column('diff_json', sa.Text(), nullable=False),
    sa.Column('at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('auditlog', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auditlog_at'), ['at'], unique=False)
        batch_op.create_index(batch_op.f('ix_auditlog_user_id'), ['user_id'], unique=False)

    op.create_table('contest',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('competition_year', sa.Integer(), nullable=False),
    sa.Column('season', sa.String(), nullable=False),
    sa.Column('contest_type', sa.String(), nullable=True),
    sa.Column('format', sa.String(), nullable=False),
    sa.Column('division', sa.String(), nullable=True),
    sa.Column('total_teams', sa.Integer(), nullable=True),
    sa.Column('school_teams_count', sa.Integer(), nullable=True),
    sa.Column('rated', sa.Boolean(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('weight_source', sa.String(), nullable=False),
    sa.Column('source_file', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contest', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contest_competition_year'), ['competition_year'], unique=False)
        batch_op.create_index(batch_op.f('ix_contest_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_contest_season'), ['season'], unique=False)
        batch_op.create_index(batch_op.f('ix_contest_source_type'), ['source_type'], unique=False)

    op.create_table('importbatch',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_version', sa.Integer(), nullable=False),
    sa.Column('rating_algorithm', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ojcontest',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('rated', sa.Boolean(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ojcontest', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ojcontest_date'), ['date'], unique=False)

    op.create_table('player',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('handle', sa.String(), nullable=True),
    sa.Column('grade', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.Column('updated_at', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('handle')
    )
    op.create_table('team',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('member_key', sa.String(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.Column('updated_at', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_team_member_key'), ['member_key'], unique=True)

    op.create_table('ojaccount',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.String(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('handle', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform', 'handle', name='uq_ojaccount_platform_handle')
    )
    with op.batch_alter_table('ojaccount', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ojaccount_player_id'), ['player_id'], unique=False)

    op.create_table('ojcontestresult',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('oj_contest_id', sa.String(), nullable=False),
    sa.Column('player_id', sa.String(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('handle', sa.String(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('rating_before', sa.Integer(), nullable=True),
    sa.Column('rating_after', sa.Integer(), nullable=True),
    sa.Column('delta', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['oj_contest_id'], ['ojcontest.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ojcontestresult', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ojcontestresult_oj_contest_id'), ['oj_contest_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ojcontestresult_player_id'), ['player_id'], unique=False)

    op.create_table('ojsnapshot',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.String(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('handle', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('rating', sa.String(), nullable=True),
    sa.Column('rating_numeric', sa.Integer(), nullable=True),
    sa.Column('solve_count', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ojsnapshot', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ojsnapshot_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_ojsnapshot_player_id'), ['player_id'], unique=False)

    op.create_table('playeralias',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.String(), nullable=False),
    sa.Column('alias', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'alias', name='uq_playeralias_player_alias')
    )
    with op.batch_alter_table('playeralias', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_playeralias_player_id'), ['player_id'], unique=False)

    op.create_table('ratingevent',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('player_id', sa.String(), nullable=False),
    sa.Column('team_id', sa.String(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('competition_year', sa.Integer(), nullable=False),
    sa.Column('season', sa.String(), nullable=False),
    sa.Column('contest_type', sa.String(), nullable=True),
    sa.Column('contest_format', sa.String(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id')
    )
    with op.batch_alter_table('ratingevent', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ratingevent_competition_year'), ['competition_year'], unique=False)
        batch_op.create_index(batch_op.f('ix_ratingevent_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_ratingevent_player_id'), ['player_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ratingevent_season'), ['season'], unique=False)
        batch_op.create_index(batch_op.f('ix_ratingevent_source_type'), ['source_type'], unique=False)

    op.create_table('standing',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contest_id', sa.String(), nullable=False),
    sa.Column('team_id', sa.String(), nullable=True),
    sa.Column('team_name', sa.String(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('school_rank', sa.Integer(), nullable=True),
    sa.Column('award', sa.String(), nullable=True),
    sa.Column('solved', sa.Integer(), nullable=True),
    sa.Column('penalty', sa.Integer(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('manually_added', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['contest_id'], ['contest.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('standing', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_standing_contest_id'), ['contest_id'], unique=False)

    op.create_table('teamalias',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('team_id', sa.String(), nullable=False),
    sa.Column('alias', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('teamalias', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teamalias_team_id'), ['team_id'], unique=False)

    op.create_table('teammember',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('team_id', sa.String(), nullable=False),
    sa.Column('player_id', sa.String(), nullable=False),
    sa.Column('seat', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('teammember', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teammember_player_id'), ['player_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_teammember_team_id'), ['team_id'], unique=False)

    op.create_table('standingmember',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('standing_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.ForeignKeyConstraint(['standing_id'], ['standing.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('standingmember', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_standingmember_player_id'), ['player_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_standingmember_standing_id'), ['standing_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('standingmember', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_standingmember_standing_id'))
        batch_op.drop_index(batch_op.f('ix_standingmember_player_id'))

    op.drop_table('standingmember')
    with op.batch_alter_table('teammember', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teammember_team_id'))
        batch_op.drop_index(batch_op.f('ix_teammember_player_id'))

    op.drop_table('teammember')
    with op.batch_alter_table('teamalias', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teamalias_team_id'))

    op.drop_table('teamalias')
    with op.batch_alter_table('standing', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_standing_contest_id'))

    op.drop_table('standing')
    with op.batch_alter_table('ratingevent', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ratingevent_source_type'))
        batch_op.drop_index(batch_op.f('ix_ratingevent_season'))
        batch_op.drop_index(batch_op.f('ix_ratingevent_player_id'))
        batch_op.drop_index(batch_op.f('ix_ratingevent_date'))
        batch_op.drop_index(batch_op.f('ix_ratingevent_competition_year'))

    op.drop_table('ratingevent')
    with op.batch_alter_table('playeralias', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_playeralias_player_id'))

    op.drop_table('playeralias')
    with op.batch_alter_table('ojsnapshot', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ojsnapshot_player_id'))
        batch_op.drop_index(batch_op.f('ix_ojsnapshot_date'))

    op.drop_table('ojsnapshot')
    with op.batch_alter_table('ojcontestresult', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ojcontestresult_player_id'))
        batch_op.drop_index(batch_op.f('ix_ojcontestresult_oj_contest_id'))

    op.drop_table('ojcontestresult')
    with op.batch_alter_table('ojaccount', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ojaccount_player_id'))

    op.drop_table('ojaccount')
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_team_member_key'))

    op.drop_table('team')
    op.drop_table('player')
    with op.batch_alter_table('ojcontest', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ojcontest_date'))

    op.drop_table('ojcontest')
    op.drop_table('meta')
    op.drop_table('importbatch')
    with op.batch_alter_table('contest', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contest_source_type'))
        batch_op.drop_index(batch_op.f('ix_contest_season'))
        batch_op.drop_index(batch_op.f('ix_contest_date'))
        batch_op.drop_index(batch_op.f('ix_contest_competition_year'))

    op.drop_table('contest')
    with op.batch_alter_table('auditlog', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auditlog_user_id'))
        batch_op.drop_index(batch_op.f('ix_auditlog_at'))

    op.drop_table('auditlog')
    # ### end Alembic commands ###
