"""points tables

Revision ID: bb6e383f49c0
Revises: 0001_baseline
Create Date: 2026-09-30 11:45:41.189227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0002_points'
down_revision = '0001_baseline'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pointsevent',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('entity', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('max_value', sa.Integer(), nullable=False),
    sa.Column('n_teams', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pointsevent', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pointsevent_date'), ['date'], unique=False)

    op.create_table('pointsclaim',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('entity', sa.String(), nullable=False),
    sa.Column('player_id', sa.String(), nullable=True),
    sa.Column('team_id', sa.String(), nullable=True),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('submitted_by', sa.Integer(), nullable=False),
    sa.Column('decided_by', sa.Integer(), nullable=True),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['pointsevent.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pointsclaim', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pointsclaim_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pointsclaim_player_id'), ['player_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pointsclaim_team_id'), ['team_id'], unique=False)
        batch_op.create_index('uq_pointsclaim_event_player', ['event_id', 'player_id'], unique=True, sqlite_where=sa.text("player_id IS NOT NULL AND status != 'rejected'"))
        batch_op.create_index('uq_pointsclaim_event_team', ['event_id', 'team_id'], unique=True, sqlite_where=sa.text("team_id IS NOT NULL AND status != 'rejected'"))

    op.create_table('pointsentry',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('owner_type', sa.String(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('points', sa.Float(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('claim_id', sa.Integer(), nullable=True),
    sa.Column('team_context', sa.String(), nullable=True),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['claim_id'], ['pointsclaim.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['pointsevent.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pointsentry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pointsentry_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_pointsentry_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pointsentry_owner_id'), ['owner_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pointsentry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pointsentry_owner_id'))
        batch_op.drop_index(batch_op.f('ix_pointsentry_event_id'))
        batch_op.drop_index(batch_op.f('ix_pointsentry_date'))

    op.drop_table('pointsentry')
    with op.batch_alter_table('pointsclaim', schema=None) as batch_op:
        batch_op.drop_index('uq_pointsclaim_event_team', sqlite_where=sa.text("team_id IS NOT NULL AND status != 'rejected'"))
        batch_op.drop_index('uq_pointsclaim_event_player', sqlite_where=sa.text("player_id IS NOT NULL AND status != 'rejected'"))
        batch_op.drop_index(batch_op.f('ix_pointsclaim_team_id'))
        batch_op.drop_index(batch_op.f('ix_pointsclaim_player_id'))
        batch_op.drop_index(batch_op.f('ix_pointsclaim_event_id'))

    op.drop_table('pointsclaim')
    with op.batch_alter_table('pointsevent', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pointsevent_date'))

    op.drop_table('pointsevent')
    # ### end Alembic commands ###
